start_port: 20000 # Starting port number for the servers, default is 20000
stream_type: "p2p" # "fullmesh" or "incast" or "p2p", default is "incast"
qp_num: 10 # Number of Queue Pairs per client-server pair, default is 10
message_size_bytes: 4096 # Message size in bytes, default is 4096
output_base: "./generated_scripts" # default is "./generated_scripts"
waiting_time_seconds: 15 # Time to wait before starting client scripts, default is 15
speed: 400 # in Gbps, used for theoretical bandwidth calculation, default is 400
rdma_cm: false # Whether to use RDMA CM for connection management, default is false

report:
  enable: true # Whether to enable report generation, default is true
  dir: "/root" # Directory to save reports, default is "/root"

run:
  infinitely: true # Whether to run the test infinitely, default is false
  duration_seconds: 10 # Duration of the test in seconds if not running infinitely, default is 10

server:
  hostname:
  - "cetus-g88-094"
  - "cetus-g88-065"
  hca:
  - "mlx5_0"
  - "mlx5_1"
client:
  hostname:
  - "cetus-g88-061"
  - "cetus-g88-062"
  hca:
  - "mlx5_0"
  - "mlx5_1"
