package cmd

import (
	"fmt"
	v0 "xnetperf/internal/v0"

	"github.com/spf13/cobra"
)

var cleanupRemote bool

var collectCmd = &cobra.Command{
	Use:   "collect",
	Short: "Collect report files from remote hosts",
	Long: `Collect report JSON files generated by ib_write_bw from all configured hosts
and organize them in local reports directory by hostname.

The --cleanup flag can be used to automatically delete remote report files 
after successful collection. Use with caution as this operation is irreversible.

Examples:
  # Collect files without cleanup
  xnetperf collect

  # Collect files and cleanup remote files after success
  xnetperf collect --cleanup`,
	Run: func(cmd *cobra.Command, args []string) {
		cfg := GetConfig()

		if !cfg.Report.Enable {
			fmt.Println("Report is not enabled in config. No files to collect.")
			return
		}

		v0.ExecCollectCommand(cfg, cleanupRemote)
	},
}

func init() {
	collectCmd.Flags().BoolVar(&cleanupRemote, "cleanup", true, "Delete remote report files after successful collection")
}
