package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"xnetperf/config"
	"xnetperf/pkg/tools"

	"github.com/spf13/cobra"
)

var cleanupRemote bool

var collectCmd = &cobra.Command{
	Use:   "collect",
	Short: "Collect report files from remote hosts",
	Long: `Collect report JSON files generated by ib_write_bw from all configured hosts
and organize them in local reports directory by hostname.

The --cleanup flag can be used to automatically delete remote report files 
after successful collection. Use with caution as this operation is irreversible.

Examples:
  # Collect files without cleanup
  xnetperf collect

  # Collect files and cleanup remote files after success
  xnetperf collect --cleanup`,
	Run: func(cmd *cobra.Command, args []string) {
		cfg, err := config.LoadConfig(cfgFile)
		if err != nil {
			fmt.Printf("Error reading config: %v\n", err)
			os.Exit(1)
		}

		if !cfg.Report.Enable {
			fmt.Println("Report is not enabled in config. No files to collect.")
			return
		}

		execCollectCommand(cfg)
	},
}

func init() {
	collectCmd.Flags().BoolVar(&cleanupRemote, "cleanup", false, "Delete remote report files after successful collection")
}

func cleanupLocalFiles(reportsDir string, hosts map[string]bool) {
	fmt.Printf("Cleaning up existing local report files...\n")

	for hostname := range hosts {
		hostDir := filepath.Join(reportsDir, hostname)

		// 检查主机目录是否存在
		if _, err := os.Stat(hostDir); os.IsNotExist(err) {
			continue // 目录不存在，跳过
		}

		// 查找该主机的所有JSON文件
		pattern := filepath.Join(hostDir, "*.json")
		files, err := filepath.Glob(pattern)
		if err != nil {
			fmt.Printf("   [WARNING] ⚠️  %s: Error finding local files: %v\n", hostname, err)
			continue
		}

		if len(files) > 0 {
			// 删除找到的文件
			for _, file := range files {
				if err := os.Remove(file); err != nil {
					fmt.Printf("   [WARNING] ⚠️  %s: Failed to remove %s: %v\n", hostname, file, err)
				}
			}
			fmt.Printf("   [CLEANUP] 🧹 %s: Removed %d existing local files\n", hostname, len(files))
		}
	}
	fmt.Println()
}

func execCollectCommand(cfg *config.Config) error {
	// 创建本地reports目录
	reportsDir := "reports"

	// Remove existing reports directory if it exists
	if _, err := os.Stat(reportsDir); err == nil {
		err = os.RemoveAll(reportsDir)
		if err != nil {
			fmt.Printf("Error removing existing reports directory: %v\n", err)
			return err
		}
		fmt.Printf("Removed existing reports directory\n")
	}

	// Create new reports directory
	err := os.MkdirAll(reportsDir, 0755)
	if err != nil {
		fmt.Printf("Error creating reports directory: %v\n", err)
		return err
	}

	// 获取所有主机列表
	allHosts := make(map[string]bool)
	for _, host := range cfg.Server.Hostname {
		allHosts[host] = true
	}
	for _, host := range cfg.Client.Hostname {
		allHosts[host] = true
	}

	// 在收集前清理本地已存在的报告文件
	cleanupLocalFiles(reportsDir, allHosts)

	var wg sync.WaitGroup
	fmt.Printf("Collecting reports from %d hosts...\n", len(allHosts))

	for hostname := range allHosts {
		wg.Add(1)
		go func(host string) {
			defer wg.Done()
			collectFromHost(host, cfg.Report.Dir, reportsDir, cfg.SSH.PrivateKey, cfg.SSH.User)
		}(hostname)
	}

	wg.Wait()
	fmt.Printf("Report collection completed. Files saved to '%s' directory.\n", reportsDir)
	return nil
}

func collectFromHost(hostname, remoteDir, localBaseDir, sshKeyPath, user string) {
	// 为每个主机创建本地子目录
	hostDir := filepath.Join(localBaseDir, hostname)
	err := os.MkdirAll(hostDir, 0755)
	if err != nil {
		fmt.Printf("Error creating directory for host %s: %v\n", hostname, err)
		return
	}

	fmt.Printf("-> Collecting reports from %s...\n", hostname)

	// 使用scp收集属于当前主机的JSON报告文件（按主机名匹配）
	// scp hostname:remoteDir/*hostname*.json localDir/
	scpCmd := fmt.Sprintf("%s/*%s*.json", remoteDir, hostname)
	cmd := exec.Command("scp", fmt.Sprintf("%s:%s", hostname, scpCmd), hostDir+"/")

	output, err := cmd.CombinedOutput()
	if err != nil {
		// 检查是否是因为没有匹配的文件
		if string(output) != "" {
			fmt.Printf("   [WARNING] ⚠️  %s: %s\n", hostname, string(output))
		} else {
			fmt.Printf("   [WARNING] ⚠️  %s: No report files found or scp failed: %v\n", hostname, err)
		}
		return
	}

	// 计算收集到的文件数量
	files, err := filepath.Glob(filepath.Join(hostDir, "*.json"))
	if err != nil {
		fmt.Printf("   [ERROR] ❌ %s: Error counting files: %v\n", hostname, err)
		return
	}

	if len(files) > 0 {
		fmt.Printf("   [SUCCESS] ✅ %s: Collected %d report files\n", hostname, len(files))

		// 仅在启用cleanup标志时清理远程主机上的报告文件
		if cleanupRemote {
			cleanupRemoteFiles(hostname, remoteDir, sshKeyPath, user)
		}
	} else {
		fmt.Printf("   [INFO] ℹ️  %s: No report files found\n", hostname)
	}
}

func cleanupRemoteFiles(hostname, remoteDir, sshKeyPath, user string) {
	fmt.Printf("   [CLEANUP] 🧹 %s: Cleaning up remote report files...\n", hostname)

	// 首先检查远程目录中是否还有属于当前主机的JSON文件
	checkCmd := fmt.Sprintf("ls %s/*%s*.json 2>/dev/null | wc -l", remoteDir, hostname)
	checkExec := tools.BuildSSHCommand(hostname, checkCmd, sshKeyPath, user)

	checkOutput, err := checkExec.CombinedOutput()
	if err != nil {
		fmt.Printf("   [WARNING] ⚠️  %s: Failed to check remote files: %v\n", hostname, err)
		return
	}

	// 如果没有文件需要清理，则跳过
	if string(checkOutput) == "0\n" {
		fmt.Printf("   [CLEANUP] ℹ️  %s: No remote files to cleanup\n", hostname)
		return
	}

	// 使用SSH删除远程主机上属于当前主机的JSON报告文件（安全匹配）
	rmCmd := fmt.Sprintf("rm -f %s/*%s*.json", remoteDir, hostname)
	cmd := tools.BuildSSHCommand(hostname, rmCmd, sshKeyPath, user)

	output, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Printf("   [WARNING] ⚠️  %s: Failed to cleanup remote files: %v\n", hostname, err)
		if len(output) > 0 {
			fmt.Printf("   [WARNING] ⚠️  %s: SSH output: %s\n", hostname, string(output))
		}
		return
	}

	// 验证清理是否成功
	verifyCmd := fmt.Sprintf("ls %s/*%s*.json 2>/dev/null | wc -l", remoteDir, hostname)
	verifyExec := tools.BuildSSHCommand(hostname, verifyCmd, sshKeyPath, user)

	verifyOutput, err := verifyExec.CombinedOutput()
	if err == nil && string(verifyOutput) == "0\n" {
		fmt.Printf("   [CLEANUP] ✅ %s: Remote files cleaned up successfully\n", hostname)
	} else {
		fmt.Printf("   [WARNING] ⚠️  %s: Cleanup verification failed\n", hostname)
	}
}
